-- AlterTable
ALTER TABLE "Payment" ADD COLUMN "vatPercentage" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Payment" ADD COLUMN "vatGbp" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Payment" ADD COLUMN "totalAmountGbp" DOUBLE PRECISION NOT NULL DEFAULT 0;

UPDATE "Payment"
SET "totalAmountGbp" = "amountGbp";
