CREATE TYPE "CompanyType" AS ENUM ('SOLE_TRADER', 'LIMITED_COMPANY', 'PARTNERSHIP', 'LIMITED_LIABILITY_PARTNERSHIP', 'PUBLIC_LIMITED_COMPANY', 'OTHER');

ALTER TABLE "RetailerProfile" ADD COLUMN "companyType" "CompanyType" NOT NULL DEFAULT 'LIMITED_COMPANY';

UPDATE "RetailerProfile" SET "companyType" = 'SOLE_TRADER' WHERE "isSoleTrader" = true;
